# Generated by Django 5.0.3 on 2024-03-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_alter_release_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/releases/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.release')),
            ],
        ),
        migrations.DeleteModel(
            name='ReleaseImage',
        ),
    ]
