# Generated by Django 3.1.1 on 2024-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_auto_20240328_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='link_to_purchase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='release',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
