# Generated by Django 5.0.3 on 2024-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_image_delete_releaseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='bandcamp_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
