# Generated by Django 3.1.1 on 2024-04-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_auto_20240401_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='preorder_date',
        ),
    ]
